<?php

use Illuminate\Database\Seeder;

class NacionalidadesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table("nacionalidades")->insert([ "id" => 1, "nacionalidad" => "Venezolana" ]);
			DB::table("nacionalidades")->insert([ "id" => 2, "nacionalidad" => "Afgana" ]);
			DB::table("nacionalidades")->insert([ "id" => 3, "nacionalidad" => "Albanesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 4, "nacionalidad" => "Alemana" ]);
			DB::table("nacionalidades")->insert([ "id" => 5, "nacionalidad" => "Alto volteña" ]);
			DB::table("nacionalidades")->insert([ "id" => 6, "nacionalidad" => "Andorrana" ]);
			DB::table("nacionalidades")->insert([ "id" => 7, "nacionalidad" => "Angoleña" ]);
			DB::table("nacionalidades")->insert([ "id" => 8, "nacionalidad" => "Argelina" ]);
			DB::table("nacionalidades")->insert([ "id" => 9, "nacionalidad" => "Argentina" ]);
			DB::table("nacionalidades")->insert([ "id" => 10, "nacionalidad" => "Australiana" ]);
			DB::table("nacionalidades")->insert([ "id" => 11, "nacionalidad" => "Austriaca" ]);
			DB::table("nacionalidades")->insert([ "id" => 12, "nacionalidad" => "Bahamesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 13, "nacionalidad" => "Bahreina" ]);
			DB::table("nacionalidades")->insert([ "id" => 14, "nacionalidad" => "Bangladesha" ]);
			DB::table("nacionalidades")->insert([ "id" => 15, "nacionalidad" => "Barbadesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 16, "nacionalidad" => "Belga" ]);
			DB::table("nacionalidades")->insert([ "id" => 17, "nacionalidad" => "Beliceña" ]);
			DB::table("nacionalidades")->insert([ "id" => 18, "nacionalidad" => "Bermudesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 19, "nacionalidad" => "Birmana" ]);
			DB::table("nacionalidades")->insert([ "id" => 20, "nacionalidad" => "Boliviana" ]);
			DB::table("nacionalidades")->insert([ "id" => 21, "nacionalidad" => "Botswanesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 22, "nacionalidad" => "Brasileña" ]);
			DB::table("nacionalidades")->insert([ "id" => 23, "nacionalidad" => "Bulgara" ]);
			DB::table("nacionalidades")->insert([ "id" => 24, "nacionalidad" => "Burundesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 25, "nacionalidad" => "Butana" ]);
			DB::table("nacionalidades")->insert([ "id" => 26, "nacionalidad" => "Camboyana" ]);
			DB::table("nacionalidades")->insert([ "id" => 27, "nacionalidad" => "Camerunesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 28, "nacionalidad" => "Canadiense" ]);
			DB::table("nacionalidades")->insert([ "id" => 29, "nacionalidad" => "Centroafricana" ]);
			DB::table("nacionalidades")->insert([ "id" => 30, "nacionalidad" => "Chadeña" ]);
			DB::table("nacionalidades")->insert([ "id" => 31, "nacionalidad" => "Checoslovaca" ]);
			DB::table("nacionalidades")->insert([ "id" => 32, "nacionalidad" => "Chilena" ]);
			DB::table("nacionalidades")->insert([ "id" => 33, "nacionalidad" => "China" ]);
			DB::table("nacionalidades")->insert([ "id" => 34, "nacionalidad" => "China" ]);
			DB::table("nacionalidades")->insert([ "id" => 35, "nacionalidad" => "Chipriota" ]);
			DB::table("nacionalidades")->insert([ "id" => 36, "nacionalidad" => "Colombiana" ]);
			DB::table("nacionalidades")->insert([ "id" => 37, "nacionalidad" => "Congoleña" ]);
			DB::table("nacionalidades")->insert([ "id" => 38, "nacionalidad" => "Costarricense" ]);
			DB::table("nacionalidades")->insert([ "id" => 39, "nacionalidad" => "Cubana" ]);
			DB::table("nacionalidades")->insert([ "id" => 40, "nacionalidad" => "Dahoneya" ]);
			DB::table("nacionalidades")->insert([ "id" => 41, "nacionalidad" => "Danes" ]);
			DB::table("nacionalidades")->insert([ "id" => 42, "nacionalidad" => "Dominicana" ]);
			DB::table("nacionalidades")->insert([ "id" => 43, "nacionalidad" => "Ecuatoriana" ]);
			DB::table("nacionalidades")->insert([ "id" => 44, "nacionalidad" => "Egipcia" ]);
			DB::table("nacionalidades")->insert([ "id" => 45, "nacionalidad" => "Emirata" ]);
			DB::table("nacionalidades")->insert([ "id" => 46, "nacionalidad" => "Escosesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 47, "nacionalidad" => "Eslovaca" ]);
			DB::table("nacionalidades")->insert([ "id" => 48, "nacionalidad" => "Española" ]);
			DB::table("nacionalidades")->insert([ "id" => 49, "nacionalidad" => "Estona" ]);
			DB::table("nacionalidades")->insert([ "id" => 50, "nacionalidad" => "Etiope" ]);
			DB::table("nacionalidades")->insert([ "id" => 51, "nacionalidad" => "Fijena" ]);
			DB::table("nacionalidades")->insert([ "id" => 52, "nacionalidad" => "Filipina" ]);
			DB::table("nacionalidades")->insert([ "id" => 53, "nacionalidad" => "Finlandesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 54, "nacionalidad" => "Francesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 55, "nacionalidad" => "Gabiana" ]);
			DB::table("nacionalidades")->insert([ "id" => 56, "nacionalidad" => "Gabona" ]);
			DB::table("nacionalidades")->insert([ "id" => 57, "nacionalidad" => "Galesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 58, "nacionalidad" => "Ghanesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 59, "nacionalidad" => "Granadeña" ]);
			DB::table("nacionalidades")->insert([ "id" => 60, "nacionalidad" => "Griega" ]);
			DB::table("nacionalidades")->insert([ "id" => 61, "nacionalidad" => "Guatemalteca" ]);
			DB::table("nacionalidades")->insert([ "id" => 62, "nacionalidad" => "Guinesa Ecuatoriana" ]);
			DB::table("nacionalidades")->insert([ "id" => 63, "nacionalidad" => "Guinesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 64, "nacionalidad" => "Guyanesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 65, "nacionalidad" => "Haitiana" ]);
			DB::table("nacionalidades")->insert([ "id" => 66, "nacionalidad" => "Holandesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 67, "nacionalidad" => "Hondureña" ]);
			DB::table("nacionalidades")->insert([ "id" => 68, "nacionalidad" => "Hungara" ]);
			DB::table("nacionalidades")->insert([ "id" => 69, "nacionalidad" => "India" ]);
			DB::table("nacionalidades")->insert([ "id" => 70, "nacionalidad" => "Indonesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 71, "nacionalidad" => "Inglesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 72, "nacionalidad" => "Iraki" ]);
			DB::table("nacionalidades")->insert([ "id" => 73, "nacionalidad" => "Irani" ]);
			DB::table("nacionalidades")->insert([ "id" => 74, "nacionalidad" => "Irlandesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 75, "nacionalidad" => "Islandesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 76, "nacionalidad" => "Israeli" ]);
			DB::table("nacionalidades")->insert([ "id" => 77, "nacionalidad" => "Italiana" ]);
			DB::table("nacionalidades")->insert([ "id" => 78, "nacionalidad" => "Jamaiquina" ]);
			DB::table("nacionalidades")->insert([ "id" => 79, "nacionalidad" => "Japonesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 80, "nacionalidad" => "Jordana" ]);
			DB::table("nacionalidades")->insert([ "id" => 81, "nacionalidad" => "Katensa" ]);
			DB::table("nacionalidades")->insert([ "id" => 82, "nacionalidad" => "Keniana" ]);
			DB::table("nacionalidades")->insert([ "id" => 83, "nacionalidad" => "Kuwaiti" ]);
			DB::table("nacionalidades")->insert([ "id" => 84, "nacionalidad" => "Laosiana" ]);
			DB::table("nacionalidades")->insert([ "id" => 85, "nacionalidad" => "Leonesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 86, "nacionalidad" => "Lesothensa" ]);
			DB::table("nacionalidades")->insert([ "id" => 87, "nacionalidad" => "Letonesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 88, "nacionalidad" => "Libanesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 89, "nacionalidad" => "Liberiana" ]);
			DB::table("nacionalidades")->insert([ "id" => 90, "nacionalidad" => "Libeña" ]);
			DB::table("nacionalidades")->insert([ "id" => 91, "nacionalidad" => "Liechtenstein" ]);
			DB::table("nacionalidades")->insert([ "id" => 92, "nacionalidad" => "Lituana" ]);
			DB::table("nacionalidades")->insert([ "id" => 93, "nacionalidad" => "Luxemburgo" ]);
			DB::table("nacionalidades")->insert([ "id" => 94, "nacionalidad" => "Madagascar" ]);
			DB::table("nacionalidades")->insert([ "id" => 95, "nacionalidad" => "Malaca" ]);
			DB::table("nacionalidades")->insert([ "id" => 96, "nacionalidad" => "Malawi" ]);
			DB::table("nacionalidades")->insert([ "id" => 97, "nacionalidad" => "Maldivas" ]);
			DB::table("nacionalidades")->insert([ "id" => 98, "nacionalidad" => "Mali" ]);
			DB::table("nacionalidades")->insert([ "id" => 99, "nacionalidad" => "Maltesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 100, "nacionalidad" => "Marfilesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 101, "nacionalidad" => "Marroqui" ]);
			DB::table("nacionalidades")->insert([ "id" => 102, "nacionalidad" => "Mauricio" ]);
			DB::table("nacionalidades")->insert([ "id" => 103, "nacionalidad" => "Mauritana" ]);
			DB::table("nacionalidades")->insert([ "id" => 104, "nacionalidad" => "Mexicana" ]);
			DB::table("nacionalidades")->insert([ "id" => 105, "nacionalidad" => "Monaco" ]);
			DB::table("nacionalidades")->insert([ "id" => 106, "nacionalidad" => "Mongolesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 107, "nacionalidad" => "Nauru" ]);
			DB::table("nacionalidades")->insert([ "id" => 108, "nacionalidad" => "Neozelandesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 109, "nacionalidad" => "Nepalesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 110, "nacionalidad" => "Nicaraguense" ]);
			DB::table("nacionalidades")->insert([ "id" => 111, "nacionalidad" => "Nigerana" ]);
			DB::table("nacionalidades")->insert([ "id" => 112, "nacionalidad" => "Nigeriana" ]);
			DB::table("nacionalidades")->insert([ "id" => 113, "nacionalidad" => "Norcoreana" ]);
			DB::table("nacionalidades")->insert([ "id" => 114, "nacionalidad" => "Norirlandesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 115, "nacionalidad" => "Norteamericana" ]);
			DB::table("nacionalidades")->insert([ "id" => 116, "nacionalidad" => "Noruega" ]);
			DB::table("nacionalidades")->insert([ "id" => 117, "nacionalidad" => "Omana" ]);
			DB::table("nacionalidades")->insert([ "id" => 118, "nacionalidad" => "Pakistani" ]);
			DB::table("nacionalidades")->insert([ "id" => 119, "nacionalidad" => "Panameña" ]);
			DB::table("nacionalidades")->insert([ "id" => 120, "nacionalidad" => "Paraguaya" ]);
			DB::table("nacionalidades")->insert([ "id" => 121, "nacionalidad" => "Peruana" ]);
			DB::table("nacionalidades")->insert([ "id" => 122, "nacionalidad" => "Polaca" ]);
			DB::table("nacionalidades")->insert([ "id" => 123, "nacionalidad" => "Portoriqueña" ]);
			DB::table("nacionalidades")->insert([ "id" => 124, "nacionalidad" => "Portuguesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 125, "nacionalidad" => "Rhodesiana" ]);
			DB::table("nacionalidades")->insert([ "id" => 126, "nacionalidad" => "Ruanda" ]);
			DB::table("nacionalidades")->insert([ "id" => 127, "nacionalidad" => "Rumana" ]);
			DB::table("nacionalidades")->insert([ "id" => 128, "nacionalidad" => "Rusa" ]);
			DB::table("nacionalidades")->insert([ "id" => 129, "nacionalidad" => "Salvadoreña" ]);
			DB::table("nacionalidades")->insert([ "id" => 130, "nacionalidad" => "Samoa Occidental" ]);
			DB::table("nacionalidades")->insert([ "id" => 131, "nacionalidad" => "San marino" ]);
			DB::table("nacionalidades")->insert([ "id" => 132, "nacionalidad" => "Saudi" ]);
			DB::table("nacionalidades")->insert([ "id" => 133, "nacionalidad" => "Senegalesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 134, "nacionalidad" => "Sikkim" ]);
			DB::table("nacionalidades")->insert([ "id" => 135, "nacionalidad" => "Singapur" ]);
			DB::table("nacionalidades")->insert([ "id" => 136, "nacionalidad" => "Siria" ]);
			DB::table("nacionalidades")->insert([ "id" => 137, "nacionalidad" => "Somalia" ]);
			DB::table("nacionalidades")->insert([ "id" => 138, "nacionalidad" => "Sovietica" ]);
			DB::table("nacionalidades")->insert([ "id" => 139, "nacionalidad" => "Sri Lanka" ]);
			DB::table("nacionalidades")->insert([ "id" => 140, "nacionalidad" => "Suazilandesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 141, "nacionalidad" => "Sudafricana" ]);
			DB::table("nacionalidades")->insert([ "id" => 142, "nacionalidad" => "Sudanesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 143, "nacionalidad" => "Sueca" ]);
			DB::table("nacionalidades")->insert([ "id" => 144, "nacionalidad" => "Suiza" ]);
			DB::table("nacionalidades")->insert([ "id" => 145, "nacionalidad" => "Surcoreana" ]);
			DB::table("nacionalidades")->insert([ "id" => 146, "nacionalidad" => "Tailandesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 147, "nacionalidad" => "Tanzana" ]);
			DB::table("nacionalidades")->insert([ "id" => 148, "nacionalidad" => "Tonga" ]);
			DB::table("nacionalidades")->insert([ "id" => 149, "nacionalidad" => "Tongo" ]);
			DB::table("nacionalidades")->insert([ "id" => 150, "nacionalidad" => "Trinidad y Tobago" ]);
			DB::table("nacionalidades")->insert([ "id" => 151, "nacionalidad" => "Tunecina" ]);
			DB::table("nacionalidades")->insert([ "id" => 152, "nacionalidad" => "Turca" ]);
			DB::table("nacionalidades")->insert([ "id" => 153, "nacionalidad" => "Ugandesa" ]);
			DB::table("nacionalidades")->insert([ "id" => 154, "nacionalidad" => "Uruguaya" ]);
			DB::table("nacionalidades")->insert([ "id" => 155, "nacionalidad" => "Vaticano" ]);
			DB::table("nacionalidades")->insert([ "id" => 156, "nacionalidad" => "Vietnamita" ]);
			DB::table("nacionalidades")->insert([ "id" => 157, "nacionalidad" => "Yemen Rep Arabe" ]);
			DB::table("nacionalidades")->insert([ "id" => 158, "nacionalidad" => "Yemen Rep Dem" ]);
			DB::table("nacionalidades")->insert([ "id" => 159, "nacionalidad" => "Yugoslava" ]);
			DB::table("nacionalidades")->insert([ "id" => 160, "nacionalidad" => "Zaire" ]);
    }
}
