<?php

use Illuminate\Database\Seeder;

class PaisesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table("paises")->insert(["id" => 1, "clave" => "AU", "pais" => "Australia" ]);
			DB::table("paises")->insert(["id" => 2, "clave" => "CN", "pais" => "China" ]);
			DB::table("paises")->insert(["id" => 3, "clave" => "JP", "pais" => "Japan" ]);
			DB::table("paises")->insert(["id" => 4, "clave" => "TH", "pais" => "Thailand" ]);
			DB::table("paises")->insert(["id" => 5, "clave" => "IN", "pais" => "India" ]);
			DB::table("paises")->insert(["id" => 6, "clave" => "MY", "pais" => "Malaysia" ]);
			DB::table("paises")->insert(["id" => 7, "clave" => "KR", "pais" => "Kore" ]);
			DB::table("paises")->insert(["id" => 8, "clave" => "HK", "pais" => "Hong Kong" ]);
			DB::table("paises")->insert(["id" => 9, "clave" => "TW", "pais" => "Taiwan" ]);
			DB::table("paises")->insert(["id" => 10, "clave" => "PH", "pais" => "Philippines" ]);
			DB::table("paises")->insert(["id" => 11, "clave" => "VN", "pais" => "Vietnam" ]);
			DB::table("paises")->insert(["id" => 12, "clave" => "FR", "pais" => "France" ]);
			DB::table("paises")->insert(["id" => 13, "clave" => "EU", "pais" => "Europe" ]);
			DB::table("paises")->insert(["id" => 14, "clave" => "DE", "pais" => "Germany" ]);
			DB::table("paises")->insert(["id" => 15, "clave" => "SE", "pais" => "Sweden" ]);
			DB::table("paises")->insert(["id" => 16, "clave" => "IT", "pais" => "Italy" ]);
			DB::table("paises")->insert(["id" => 17, "clave" => "GR", "pais" => "Greece" ]);
			DB::table("paises")->insert(["id" => 18, "clave" => "ES", "pais" => "Spain" ]);
			DB::table("paises")->insert(["id" => 19, "clave" => "AT", "pais" => "Austria" ]);
			DB::table("paises")->insert(["id" => 20, "clave" => "GB", "pais" => "United Kingdom" ]);
			DB::table("paises")->insert(["id" => 21, "clave" => "NL", "pais" => "Netherlands" ]);
			DB::table("paises")->insert(["id" => 22, "clave" => "BE", "pais" => "Belgium" ]);
			DB::table("paises")->insert(["id" => 23, "clave" => "CH", "pais" => "Switzerland" ]);
			DB::table("paises")->insert(["id" => 24, "clave" => "AE", "pais" => "United Arab Emirates" ]);
			DB::table("paises")->insert(["id" => 25, "clave" => "IL", "pais" => "Israel" ]);
			DB::table("paises")->insert(["id" => 26, "clave" => "UA", "pais" => "Ukraine" ]);
			DB::table("paises")->insert(["id" => 27, "clave" => "RU", "pais" => "Russian Federation" ]);
			DB::table("paises")->insert(["id" => 28, "clave" => "KZ", "pais" => "Kazakhstan" ]);
			DB::table("paises")->insert(["id" => 29, "clave" => "PT", "pais" => "Portugal" ]);
			DB::table("paises")->insert(["id" => 30, "clave" => "SA", "pais" => "Saudi Arabia" ]);
			DB::table("paises")->insert(["id" => 31, "clave" => "DK", "pais" => "Denmark" ]);
			DB::table("paises")->insert(["id" => 32, "clave" => "IR", "pais" => "Ira" ]);
			DB::table("paises")->insert(["id" => 33, "clave" => "NO", "pais" => "Norway" ]);
			DB::table("paises")->insert(["id" => 34, "clave" => "US", "pais" => "United States" ]);
			DB::table("paises")->insert(["id" => 35, "clave" => "MX", "pais" => "México" ]);
			DB::table("paises")->insert(["id" => 36, "clave" => "CA", "pais" => "Canada" ]);
			DB::table("paises")->insert(["id" => 37, "clave" => "A1", "pais" => "Anonymous Proxy" ]);
			DB::table("paises")->insert(["id" => 38, "clave" => "SY", "pais" => "Syrian Arab Republic" ]);
			DB::table("paises")->insert(["id" => 39, "clave" => "CY", "pais" => "Cyprus" ]);
			DB::table("paises")->insert(["id" => 40, "clave" => "CZ", "pais" => "Czech Republic" ]);
			DB::table("paises")->insert(["id" => 41, "clave" => "IQ", "pais" => "Iraq" ]);
			DB::table("paises")->insert(["id" => 42, "clave" => "TR", "pais" => "Turkey" ]);
			DB::table("paises")->insert(["id" => 43, "clave" => "RO", "pais" => "Romania" ]);
			DB::table("paises")->insert(["id" => 44, "clave" => "LB", "pais" => "Lebanon" ]);
			DB::table("paises")->insert(["id" => 45, "clave" => "HU", "pais" => "Hungary" ]);
			DB::table("paises")->insert(["id" => 46, "clave" => "GE", "pais" => "Georgia" ]);
			DB::table("paises")->insert(["id" => 47, "clave" => "BR", "pais" => "Brazil" ]);
			DB::table("paises")->insert(["id" => 48, "clave" => "AZ", "pais" => "Azerbaijan" ]);
			DB::table("paises")->insert(["id" => 49, "clave" => "A2", "pais" => "Satellite Provider" ]);
			DB::table("paises")->insert(["id" => 50, "clave" => "PS", "pais" => "Palestinian Territory" ]);
			DB::table("paises")->insert(["id" => 51, "clave" => "LT", "pais" => "Lithuania" ]);
			DB::table("paises")->insert(["id" => 52, "clave" => "OM", "pais" => "Oman" ]);
			DB::table("paises")->insert(["id" => 53, "clave" => "SK", "pais" => "Slovakia" ]);
			DB::table("paises")->insert(["id" => 54, "clave" => "RS", "pais" => "Serbia" ]);
			DB::table("paises")->insert(["id" => 55, "clave" => "FI", "pais" => "Finland" ]);
			DB::table("paises")->insert(["id" => 56, "clave" => "IS", "pais" => "Iceland" ]);
			DB::table("paises")->insert(["id" => 57, "clave" => "BG", "pais" => "Bulgaria" ]);
			DB::table("paises")->insert(["id" => 58, "clave" => "SI", "pais" => "Slovenia" ]);
			DB::table("paises")->insert(["id" => 59, "clave" => "MD", "pais" => "Moldov" ]);
			DB::table("paises")->insert(["id" => 60, "clave" => "MK", "pais" => "Macedonia" ]);
			DB::table("paises")->insert(["id" => 61, "clave" => "LI", "pais" => "Liechtenstein" ]);
			DB::table("paises")->insert(["id" => 62, "clave" => "JE", "pais" => "Jersey" ]);
			DB::table("paises")->insert(["id" => 63, "clave" => "PL", "pais" => "Poland" ]);
			DB::table("paises")->insert(["id" => 64, "clave" => "HR", "pais" => "Croatia" ]);
			DB::table("paises")->insert(["id" => 65, "clave" => "BA", "pais" => "Bosnia and Herzegovina" ]);
			DB::table("paises")->insert(["id" => 66, "clave" => "EE", "pais" => "Estonia" ]);
			DB::table("paises")->insert(["id" => 67, "clave" => "LV", "pais" => "Latvia" ]);
			DB::table("paises")->insert(["id" => 68, "clave" => "JO", "pais" => "Jordan" ]);
			DB::table("paises")->insert(["id" => 69, "clave" => "KG", "pais" => "Kyrgyzstan" ]);
			DB::table("paises")->insert(["id" => 70, "clave" => "RE", "pais" => "Reunion" ]);
			DB::table("paises")->insert(["id" => 71, "clave" => "IE", "pais" => "Ireland" ]);
			DB::table("paises")->insert(["id" => 72, "clave" => "LY", "pais" => "Libya" ]);
			DB::table("paises")->insert(["id" => 73, "clave" => "LU", "pais" => "Luxembourg" ]);
			DB::table("paises")->insert(["id" => 74, "clave" => "AM", "pais" => "Armenia" ]);
			DB::table("paises")->insert(["id" => 75, "clave" => "VG", "pais" => "Virgin Island" ]);
			DB::table("paises")->insert(["id" => 76, "clave" => "YE", "pais" => "Yemen" ]);
			DB::table("paises")->insert(["id" => 77, "clave" => "BY", "pais" => "Belarus" ]);
			DB::table("paises")->insert(["id" => 78, "clave" => "GI", "pais" => "Gibraltar" ]);
			DB::table("paises")->insert(["id" => 79, "clave" => "MQ", "pais" => "Martinique" ]);
			DB::table("paises")->insert(["id" => 80, "clave" => "PA", "pais" => "Panama" ]);
			DB::table("paises")->insert(["id" => 81, "clave" => "DO", "pais" => "Dominican Republic" ]);
			DB::table("paises")->insert(["id" => 82, "clave" => "GU", "pais" => "Guam" ]);
			DB::table("paises")->insert(["id" => 83, "clave" => "PR", "pais" => "Puerto Rico" ]);
			DB::table("paises")->insert(["id" => 84, "clave" => "VI", "pais" => "Virgin Island" ]);
			DB::table("paises")->insert(["id" => 85, "clave" => "MN", "pais" => "Mongolia" ]);
			DB::table("paises")->insert(["id" => 86, "clave" => "NZ", "pais" => "New Zealand" ]);
			DB::table("paises")->insert(["id" => 87, "clave" => "SG", "pais" => "Singapore" ]);
			DB::table("paises")->insert(["id" => 88, "clave" => "ID", "pais" => "Indonesia" ]);
			DB::table("paises")->insert(["id" => 89, "clave" => "NP", "pais" => "Nepal" ]);
			DB::table("paises")->insert(["id" => 90, "clave" => "PG", "pais" => "Papua New Guinea" ]);
			DB::table("paises")->insert(["id" => 91, "clave" => "PK", "pais" => "Pakistan" ]);
			DB::table("paises")->insert(["id" => 92, "clave" => "AP", "pais" => "Asia/Pacific Region" ]);
			DB::table("paises")->insert(["id" => 93, "clave" => "BS", "pais" => "Bahamas" ]);
			DB::table("paises")->insert(["id" => 94, "clave" => "LC", "pais" => "Saint Lucia" ]);
			DB::table("paises")->insert(["id" => 95, "clave" => "AR", "pais" => "Argentina" ]);
			DB::table("paises")->insert(["id" => 96, "clave" => "BD", "pais" => "Bangladesh" ]);
			DB::table("paises")->insert(["id" => 97, "clave" => "TK", "pais" => "Tokelau" ]);
			DB::table("paises")->insert(["id" => 98, "clave" => "KH", "pais" => "Cambodia" ]);
			DB::table("paises")->insert(["id" => 99, "clave" => "MO", "pais" => "Macau" ]);
			DB::table("paises")->insert(["id" => 100, "clave" => "MV", "pais" => "Maldives" ]);
			DB::table("paises")->insert(["id" => 101, "clave" => "AF", "pais" => "Afghanistan" ]);
			DB::table("paises")->insert(["id" => 102, "clave" => "NC", "pais" => "New Caledonia" ]);
			DB::table("paises")->insert(["id" => 103, "clave" => "FJ", "pais" => "Fiji" ]);
			DB::table("paises")->insert(["id" => 104, "clave" => "WF", "pais" => "Wallis and Futuna" ]);
			DB::table("paises")->insert(["id" => 105, "clave" => "QA", "pais" => "Qatar" ]);
			DB::table("paises")->insert(["id" => 106, "clave" => "AL", "pais" => "Albania" ]);
			DB::table("paises")->insert(["id" => 107, "clave" => "BZ", "pais" => "Belize" ]);
			DB::table("paises")->insert(["id" => 108, "clave" => "UZ", "pais" => "Uzbekistan" ]);
			DB::table("paises")->insert(["id" => 109, "clave" => "KW", "pais" => "Kuwait" ]);
			DB::table("paises")->insert(["id" => 110, "clave" => "ME", "pais" => "Montenegro" ]);
			DB::table("paises")->insert(["id" => 111, "clave" => "PE", "pais" => "Peru" ]);
			DB::table("paises")->insert(["id" => 112, "clave" => "BM", "pais" => "Bermuda" ]);
			DB::table("paises")->insert(["id" => 113, "clave" => "CW", "pais" => "Curacao" ]);
			DB::table("paises")->insert(["id" => 114, "clave" => "CO", "pais" => "Colombia" ]);
			DB::table("paises")->insert(["id" => 115, "clave" => "VE", "pais" => "Venezuela" ]);
			DB::table("paises")->insert(["id" => 116, "clave" => "CL", "pais" => "Chile" ]);
			DB::table("paises")->insert(["id" => 117, "clave" => "EC", "pais" => "Ecuador" ]);
			DB::table("paises")->insert(["id" => 118, "clave" => "ZA", "pais" => "South Africa" ]);
			DB::table("paises")->insert(["id" => 119, "clave" => "IM", "pais" => "Isle of Man" ]);
			DB::table("paises")->insert(["id" => 120, "clave" => "BO", "pais" => "Bolivia" ]);
			DB::table("paises")->insert(["id" => 121, "clave" => "GG", "pais" => "Guernsey" ]);
			DB::table("paises")->insert(["id" => 122, "clave" => "MT", "pais" => "Malta" ]);
			DB::table("paises")->insert(["id" => 123, "clave" => "TJ", "pais" => "Tajikistan" ]);
			DB::table("paises")->insert(["id" => 124, "clave" => "SC", "pais" => "Seychelles" ]);
			DB::table("paises")->insert(["id" => 125, "clave" => "BH", "pais" => "Bahrain" ]);
			DB::table("paises")->insert(["id" => 126, "clave" => "EG", "pais" => "Egypt" ]);
			DB::table("paises")->insert(["id" => 127, "clave" => "ZW", "pais" => "Zimbabwe" ]);
			DB::table("paises")->insert(["id" => 128, "clave" => "LR", "pais" => "Liberia" ]);
			DB::table("paises")->insert(["id" => 129, "clave" => "KE", "pais" => "Kenya" ]);
			DB::table("paises")->insert(["id" => 130, "clave" => "GH", "pais" => "Ghana" ]);
			DB::table("paises")->insert(["id" => 131, "clave" => "NG", "pais" => "Nigeria" ]);
			DB::table("paises")->insert(["id" => 132, "clave" => "TZ", "pais" => "Tanzani" ]);
			DB::table("paises")->insert(["id" => 133, "clave" => "ZM", "pais" => "Zambia" ]);
			DB::table("paises")->insert(["id" => 134, "clave" => "MG", "pais" => "Madagascar" ]);
			DB::table("paises")->insert(["id" => 135, "clave" => "AO", "pais" => "Angola" ]);
			DB::table("paises")->insert(["id" => 136, "clave" => "NA", "pais" => "Namibia" ]);
			DB::table("paises")->insert(["id" => 137, "clave" => "CI", "pais" => "Cote D'Ivoire" ]);
			DB::table("paises")->insert(["id" => 138, "clave" => "SD", "pais" => "Sudan" ]);
			DB::table("paises")->insert(["id" => 139, "clave" => "CM", "pais" => "Cameroon" ]);
			DB::table("paises")->insert(["id" => 140, "clave" => "MW", "pais" => "Malawi" ]);
			DB::table("paises")->insert(["id" => 141, "clave" => "GA", "pais" => "Gabon" ]);
			DB::table("paises")->insert(["id" => 142, "clave" => "ML", "pais" => "Mali" ]);
			DB::table("paises")->insert(["id" => 143, "clave" => "BJ", "pais" => "Benin" ]);
			DB::table("paises")->insert(["id" => 144, "clave" => "TD", "pais" => "Chad" ]);
			DB::table("paises")->insert(["id" => 145, "clave" => "BW", "pais" => "Botswana" ]);
			DB::table("paises")->insert(["id" => 146, "clave" => "CV", "pais" => "Cape Verde" ]);
			DB::table("paises")->insert(["id" => 147, "clave" => "RW", "pais" => "Rwanda" ]);
			DB::table("paises")->insert(["id" => 148, "clave" => "CG", "pais" => "Congo" ]);
			DB::table("paises")->insert(["id" => 149, "clave" => "UG", "pais" => "Uganda" ]);
			DB::table("paises")->insert(["id" => 150, "clave" => "MZ", "pais" => "Mozambique" ]);
			DB::table("paises")->insert(["id" => 151, "clave" => "GM", "pais" => "Gambia" ]);
			DB::table("paises")->insert(["id" => 152, "clave" => "LS", "pais" => "Lesotho" ]);
			DB::table("paises")->insert(["id" => 153, "clave" => "MU", "pais" => "Mauritius" ]);
			DB::table("paises")->insert(["id" => 154, "clave" => "MA", "pais" => "Morocco" ]);
			DB::table("paises")->insert(["id" => 155, "clave" => "DZ", "pais" => "Algeria" ]);
			DB::table("paises")->insert(["id" => 156, "clave" => "GN", "pais" => "Guinea" ]);
			DB::table("paises")->insert(["id" => 157, "clave" => "CD", "pais" => "Cong" ]);
			DB::table("paises")->insert(["id" => 158, "clave" => "SZ", "pais" => "Swaziland" ]);
			DB::table("paises")->insert(["id" => 159, "clave" => "BF", "pais" => "Burkina Faso" ]);
			DB::table("paises")->insert(["id" => 160, "clave" => "SL", "pais" => "Sierra Leone" ]);
			DB::table("paises")->insert(["id" => 161, "clave" => "SO", "pais" => "Somalia" ]);
			DB::table("paises")->insert(["id" => 162, "clave" => "NE", "pais" => "Niger" ]);
			DB::table("paises")->insert(["id" => 163, "clave" => "CF", "pais" => "Central African Republic" ]);
			DB::table("paises")->insert(["id" => 164, "clave" => "TG", "pais" => "Togo" ]);
			DB::table("paises")->insert(["id" => 165, "clave" => "BI", "pais" => "Burundi" ]);
			DB::table("paises")->insert(["id" => 166, "clave" => "GQ", "pais" => "Equatorial Guinea" ]);
			DB::table("paises")->insert(["id" => 167, "clave" => "SS", "pais" => "South Sudan" ]);
			DB::table("paises")->insert(["id" => 168, "clave" => "SN", "pais" => "Senegal" ]);
			DB::table("paises")->insert(["id" => 169, "clave" => "MR", "pais" => "Mauritania" ]);
			DB::table("paises")->insert(["id" => 170, "clave" => "DJ", "pais" => "Djibouti" ]);
			DB::table("paises")->insert(["id" => 171, "clave" => "KM", "pais" => "Comoros" ]);
			DB::table("paises")->insert(["id" => 172, "clave" => "IO", "pais" => "British Indian Ocean Territory" ]);
			DB::table("paises")->insert(["id" => 173, "clave" => "TN", "pais" => "Tunisia" ]);
			DB::table("paises")->insert(["id" => 174, "clave" => "GL", "pais" => "Greenland" ]);
			DB::table("paises")->insert(["id" => 175, "clave" => "VA", "pais" => "Holy See (Vatican City State)" ]);
			DB::table("paises")->insert(["id" => 176, "clave" => "CR", "pais" => "Costa Rica" ]);
			DB::table("paises")->insert(["id" => 177, "clave" => "KY", "pais" => "Cayman Islands" ]);
			DB::table("paises")->insert(["id" => 178, "clave" => "JM", "pais" => "Jamaica" ]);
			DB::table("paises")->insert(["id" => 179, "clave" => "GT", "pais" => "Guatemala" ]);
			DB::table("paises")->insert(["id" => 180, "clave" => "MH", "pais" => "Marshall Islands" ]);
			DB::table("paises")->insert(["id" => 181, "clave" => "AQ", "pais" => "Antarctica" ]);
			DB::table("paises")->insert(["id" => 182, "clave" => "BB", "pais" => "Barbados" ]);
			DB::table("paises")->insert(["id" => 183, "clave" => "AW", "pais" => "Aruba" ]);
			DB::table("paises")->insert(["id" => 184, "clave" => "MC", "pais" => "Monaco" ]);
			DB::table("paises")->insert(["id" => 185, "clave" => "AI", "pais" => "Anguilla" ]);
			DB::table("paises")->insert(["id" => 186, "clave" => "KN", "pais" => "Saint Kitts and Nevis" ]);
			DB::table("paises")->insert(["id" => 187, "clave" => "GD", "pais" => "Grenada" ]);
			DB::table("paises")->insert(["id" => 188, "clave" => "PY", "pais" => "Paraguay" ]);
			DB::table("paises")->insert(["id" => 189, "clave" => "MS", "pais" => "Montserrat" ]);
			DB::table("paises")->insert(["id" => 190, "clave" => "TC", "pais" => "Turks and Caicos Islands" ]);
			DB::table("paises")->insert(["id" => 191, "clave" => "AG", "pais" => "Antigua and Barbuda" ]);
			DB::table("paises")->insert(["id" => 192, "clave" => "TV", "pais" => "Tuvalu" ]);
			DB::table("paises")->insert(["id" => 193, "clave" => "PF", "pais" => "French Polynesia" ]);
			DB::table("paises")->insert(["id" => 194, "clave" => "SB", "pais" => "Solomon Islands" ]);
			DB::table("paises")->insert(["id" => 195, "clave" => "VU", "pais" => "Vanuatu" ]);
			DB::table("paises")->insert(["id" => 196, "clave" => "ER", "pais" => "Eritrea" ]);
			DB::table("paises")->insert(["id" => 197, "clave" => "TT", "pais" => "Trinidad and Tobago" ]);
			DB::table("paises")->insert(["id" => 198, "clave" => "AD", "pais" => "Andorra" ]);
			DB::table("paises")->insert(["id" => 199, "clave" => "HT", "pais" => "Haiti" ]);
			DB::table("paises")->insert(["id" => 200, "clave" => "SH", "pais" => "Saint Helena" ]);
			DB::table("paises")->insert(["id" => 201, "clave" => "FM", "pais" => "Micronesi" ]);
			DB::table("paises")->insert(["id" => 202, "clave" => "SV", "pais" => "El Salvador" ]);
			DB::table("paises")->insert(["id" => 203, "clave" => "HN", "pais" => "Honduras" ]);
			DB::table("paises")->insert(["id" => 204, "clave" => "UY", "pais" => "Uruguay" ]);
			DB::table("paises")->insert(["id" => 205, "clave" => "LK", "pais" => "Sri Lanka" ]);
			DB::table("paises")->insert(["id" => 206, "clave" => "EH", "pais" => "Western Sahara" ]);
			DB::table("paises")->insert(["id" => 207, "clave" => "CX", "pais" => "Christmas Island" ]);
			DB::table("paises")->insert(["id" => 208, "clave" => "WS", "pais" => "Samoa" ]);
			DB::table("paises")->insert(["id" => 209, "clave" => "SR", "pais" => "Suriname" ]);
			DB::table("paises")->insert(["id" => 210, "clave" => "CK", "pais" => "Cook Islands" ]);
			DB::table("paises")->insert(["id" => 211, "clave" => "KI", "pais" => "Kiribati" ]);
			DB::table("paises")->insert(["id" => 212, "clave" => "NU", "pais" => "Niue" ]);
			DB::table("paises")->insert(["id" => 213, "clave" => "TO", "pais" => "Tonga" ]);
			DB::table("paises")->insert(["id" => 214, "clave" => "TF", "pais" => "French Southern Territories" ]);
			DB::table("paises")->insert(["id" => 215, "clave" => "YT", "pais" => "Mayotte" ]);
			DB::table("paises")->insert(["id" => 216, "clave" => "NF", "pais" => "Norfolk Island" ]);
			DB::table("paises")->insert(["id" => 217, "clave" => "BN", "pais" => "Brunei Darussalam" ]);
			DB::table("paises")->insert(["id" => 218, "clave" => "TM", "pais" => "Turkmenistan" ]);
			DB::table("paises")->insert(["id" => 219, "clave" => "PN", "pais" => "Pitcairn Islands" ]);
			DB::table("paises")->insert(["id" => 220, "clave" => "SM", "pais" => "San Marino" ]);
			DB::table("paises")->insert(["id" => 221, "clave" => "AX", "pais" => "Aland Islands" ]);
			DB::table("paises")->insert(["id" => 222, "clave" => "FO", "pais" => "Faroe Islands" ]);
			DB::table("paises")->insert(["id" => 223, "clave" => "SJ", "pais" => "Svalbard and Jan Mayen" ]);
			DB::table("paises")->insert(["id" => 224, "clave" => "CC", "pais" => "Cocos (Keeling) Islands" ]);
			DB::table("paises")->insert(["id" => 225, "clave" => "NR", "pais" => "Nauru" ]);
			DB::table("paises")->insert(["id" => 226, "clave" => "GS", "pais" => "South Georgia and the South Sandwich Islands" ]);
			DB::table("paises")->insert(["id" => 227, "clave" => "UM", "pais" => "United States Minor Outlying Islands" ]);
			DB::table("paises")->insert(["id" => 228, "clave" => "GW", "pais" => "Guinea-Bissau" ]);
			DB::table("paises")->insert(["id" => 229, "clave" => "PW", "pais" => "Palau" ]);
			DB::table("paises")->insert(["id" => 230, "clave" => "AS", "pais" => "American Samoa" ]);
			DB::table("paises")->insert(["id" => 231, "clave" => "BT", "pais" => "Bhutan" ]);
			DB::table("paises")->insert(["id" => 232, "clave" => "GF", "pais" => "French Guiana" ]);
			DB::table("paises")->insert(["id" => 233, "clave" => "GP", "pais" => "Guadeloupe" ]);
			DB::table("paises")->insert(["id" => 234, "clave" => "MF", "pais" => "Saint Martin" ]);
			DB::table("paises")->insert(["id" => 235, "clave" => "VC", "pais" => "Saint Vincent and the Grenadines" ]);
			DB::table("paises")->insert(["id" => 236, "clave" => "PM", "pais" => "Saint Pierre and Miquelon" ]);
			DB::table("paises")->insert(["id" => 237, "clave" => "BL", "pais" => "Saint Barthelemy" ]);
			DB::table("paises")->insert(["id" => 238, "clave" => "DM", "pais" => "Dominica" ]);
			DB::table("paises")->insert(["id" => 239, "clave" => "ST", "pais" => "Sao Tome and Principe" ]);
			DB::table("paises")->insert(["id" => 240, "clave" => "KP", "pais" => "Kore" ]);
			DB::table("paises")->insert(["id" => 241, "clave" => "FK", "pais" => "Falkland Islands (Malvinas)" ]);
			DB::table("paises")->insert(["id" => 242, "clave" => "MP", "pais" => "Northern Mariana Islands" ]);
			DB::table("paises")->insert(["id" => 243, "clave" => "TL", "pais" => "Timor-Leste" ]);
			DB::table("paises")->insert(["id" => 244, "clave" => "BQ", "pais" => "Bonair" ]);
			DB::table("paises")->insert(["id" => 245, "clave" => "MM", "pais" => "Myanmar" ]);
			DB::table("paises")->insert(["id" => 246, "clave" => "NI", "pais" => "Nicaragua" ]);
			DB::table("paises")->insert(["id" => 247, "clave" => "SX", "pais" => "Sint Maarten (Dutch part)" ]);
			DB::table("paises")->insert(["id" => 248, "clave" => "GY", "pais" => "Guyana" ]);
			DB::table("paises")->insert(["id" => 249, "clave" => "LA", "pais" => "Lao People's Democratic Republic" ]);
			DB::table("paises")->insert(["id" => 250, "clave" => "CU", "pais" => "Cuba" ]);
			DB::table("paises")->insert(["id" => 251, "clave" => "ET", "pais" => "Ethiopia" ]);
    }
}
